version: 0.2
            
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
        - echo install
  pre_build:
    commands:
       - echo pre
   build:
    commands:
       - mvn package
   post_build:
     commands:
       - echo post
artifacts:
  files:
    - target\aws-code-pipeline-0.0.1-SNAPSHOT.jar
